/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Brand: typeof import('./src/components/brand.vue')['default']
    BrandForm: typeof import('./src/components/BrandForm.vue')['default']
    Button: typeof import('primevue/button')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    InputText: typeof import('primevue/inputtext')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textarea: typeof import('primevue/textarea')['default']
    TheNav: typeof import('./src/layouts/TheNav.vue')['default']
    UploadProductCategory: typeof import('./src/components/upload/UploadProductCategory.vue')['default']
    UploadProductCatgegory: typeof import('./src/components/upload/UploadProductCatgegory.vue')['default']
    UploadProductInfo: typeof import('./src/components/upload/UploadProductInfo.vue')['default']
  }
}
