/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    Brand: typeof import('./src/components/brand.vue')['default']
    BrandForm: typeof import('./src/components/BrandForm.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Editor: typeof import('primevue/editor')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Galleria: typeof import('primevue/galleria')['default']
    Image: typeof import('primevue/image')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ItemsList: typeof import('./src/components/items/ItemsList.vue')['default']
    ItemsListCard: typeof import('./src/components/items/ItemsListCard.vue')['default']
    ItemsSnb: typeof import('./src/components/items/ItemsSnb.vue')['default']
    MainItemsList: typeof import('./src/components/main/MainItemsList.vue')['default']
    MainSnb: typeof import('./src/components/MainSnb.vue')['default']
    NavCore: typeof import('./src/components/NavCore.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Snb: typeof import('./src/components/Snb.vue')['default']
    TabMenu: typeof import('primevue/tabmenu')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TheNav: typeof import('./src/layouts/TheNav.vue')['default']
    UploadProductCategory: typeof import('./src/components/upload/UploadProductCategory.vue')['default']
    UploadProductCatgegory: typeof import('./src/components/upload/UploadProductCatgegory.vue')['default']
    UploadProductDeliveryOption: typeof import('./src/components/upload/UploadProductDeliveryOption.vue')['default']
    UploadProductImage: typeof import('./src/components/upload/UploadProductImage.vue')['default']
    UploadProductInfo: typeof import('./src/components/upload/UploadProductInfo.vue')['default']
    UploadProductPrice: typeof import('./src/components/upload/UploadProductPrice.vue')['default']
    UploadProductSellingType: typeof import('./src/components/upload/UploadProductSellingType.vue')['default']
    UploadProductShippingOption: typeof import('./src/components/upload/UploadProductShippingOption.vue')['default']
  }
}
